name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  commitlint:
    name: PR title / description conforms to semantic-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npx commitlint --verbose <<< $COMMIT_MSG
        env:
          COMMIT_MSG: >
            ${{ github.event.pull_request.title }}
            
            ${{ github.event.pull_request.body }}
  breaking:
    name: Ensure breaking changes are labeled in description
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.9.0
      - name: check for breaking changes
        id: check-breaking
        run: |
          set -euo pipefail

          if ! buf breaking --against 'https://github.com/substrait-io/substrait.git#branch=main'; then
            breaking="true"
          else
            breaking="false"
          fi

          echo "::set-output name=breaking::${breaking}"
      - name: check whether the PR description includes a breaking change footer
        if: ${{ fromJson(steps.check-breaking.outputs.breaking) }}
        run: |
          set -euo pipefail
          # check PR description for a BREAKING CHANGE section if any breaking changes occurred
          grep 'BREAKING CHANGE: ' <<< $COMMIT_DESC
        env:
          COMMIT_DESC: ${{ github.event.pull_request.body }}
